### ISSUE TITLE
Requirements List - can't find a module and update to the module list to install

### ISSUE THREAD

**Issue by eperry** [conix-security/springbok#5]
Can you please add the following libraries to your requirements

reportlab
graphviz

I also can't seem to find the library in apt or on the internet that provides this module.  Some help please

```
eperry@SilverHWK:~/springbok$ python springbok.py
WARNING: There was a problem loading the table file: KeyError('p_ip_src_line_2',)
WARNING: 'p_info' not defined as a function
WARNING: Token 'WS' defined, but not used
WARNING: There is 1 unused token
Generating LALR tables
Traceback (most recent call last):
  File "springbok.py", line 7, in <module>
    from Gtk import Gtk_Main
  File "/home/eperry/springbok/Gtk/Gtk_Main.py", line 9, in <module>
    import Gtk_MenuBar
  File "/home/eperry/springbok/Gtk/Gtk_MenuBar.py", line 30, in <module>
    from Tools.ExcelToolKit import ExcelToolKit
ImportError: No module named Tools.ExcelToolKit
```

**Comment by m0rbi** [comment]
Reportlab you can grab with `pip install reportlab`. I haven't received in error for graphiz.

Like you, I am unable to make it past this error:

`File "/root/springbok/Gtk/Gtk_MenuBar.py", line 30, in <module> from Tools.ExcelToolKit import ExcelToolKit ImportError: No module named Tools.ExcelToolKit`

and all efforts to intall pygtk using pip or easy install fail with 

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UyS_0k/pygtk/`

I have also installed python-gtk2 and python-gtk2-dev from apt sources, as well as install every xlsxwriter pip package I can find.

Any guidance would be supremely helpful!

**Comment by eperry** [comment]
oh I figured out how to get those repo's I think I used the apt install python-gtk2-dev  to install pygtk

I see Tools.ExcelToolKit is in a sub directory but I don't know why it will not load.

**Comment by PhilippeDupart** [comment]
The issue was fixed with the commit six days ago.
It came from forgetting a file in the previous commit. (Tools/__init__.py)

I also updated the Readme to make the install easier.

**Comment by eperry** [comment]
Cool! when I get to work I will give it a test.  THANKS!

**Comment by sdananda** [comment]
Hi,

Getting the error attached the pix.
Let me know anyone faced the same issue and fixed.
![capture](https://user-images.githubusercontent.com/16759431/32548538-0220598e-c4ac-11e7-9a01-e9304157c3b2.JPG)
